variables:
  DOCKER_HOST_DEV: "172.16.100.101"
  SSH_USER: "devops"
  SSH_KEY: "/home/devops/.ssh/id_rsa"
  DOCKER_REGISTRY: "349355168610.dkr.ecr.us-east-1.amazonaws.com"

stages:
  - build
  - deploy

build-cicd:
  environment:
    name: test
  stage: build
  tags:
    - test-runner
  before_script:
    - $(aws ecr get-login --no-include-email --region us-east-1)
  script:
    - docker build -f docker/Dockerfile -t ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME} .
    - docker push ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}
  after_script:

deploy-cicd:
  environment:
    name: test
  stage: deploy
  tags:
    - test-runner
  before_script:
    - $(aws ecr get-login --no-include-email --region us-east-1)
  script:
    - docker stack deploy --with-registry-auth -c docker/docker-compose.yml ${CI_PROJECT_NAME}-owen
  after_script:
